spring:
  data:
    mongodb:
      uri: mongodb://101.133.229.162:27017/radar
  datasource:
    url: jdbc:mysql://101.133.229.162/radar?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: radar-admin
  redis:
    host: 101.133.229.162
#    username: default
#    password: xufxZW4OuXSirj7J91lo4L8Sh2li3MGO
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0
    port: 6379

mobile:
  info:
    path: data/soft/moble_info.csv #手机号码归属地文件
ip2region:
  db:
    path: data/soft/ip2region.db #IP地址库文件
elasticsearch:
  ip: 192.168.197.154
  port: 9300
  pool-size: 5
  cluster:
    name: elasticsearch
  url: http://127.0.0.1:9200
  username:  # 不存在就留空
  password:  #
sys:
  conf:
    app: admin # admin 或者 engine， 根据启动的项目名称进行选择
    entity-duplicate-insert: false # 事件是否允许重复插入
    mongo-restore-days: 3650 # 事件保存时间，默认3个月
    workdir: d:/radar #   工作目录
server:
  port: 6580